services:
  app:
    image: ghcr.io/jcubby86/games-app:${DOCKER_TAG:-latest}
    ports:
      - ${WEB_PORT:-80}:80
    environment:
      - NGINX_BACKEND_ADDRESS=http://backend:${NODE_PORT:-3000}
    restart: unless-stopped
    depends_on: 
      - backend
      - db

  backend:
    image: ghcr.io/jcubby86/games-backend:${DOCKER_TAG:-latest}
    environment:
      - DATABASE_URL=postgresql://postgres:${PG_PASS}@db:5432/prisma?schema=public
      - NODE_PORT=${NODE_PORT:-3000}
    restart: unless-stopped
    depends_on: 
      - db
    healthcheck:
      test:  wget --spider --tries=1 --no-verbose http://localhost:${NODE_PORT:-3000}/api/health
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 10s
      
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - /portainer/postgres/games-test:/var/lib/postgresql/data
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    
  db-seed:
    image: ghcr.io/jcubby86/games-seed:${DOCKER_TAG:-latest}
    environment:
      - DATABASE_URL=postgresql://postgres:${PG_PASS}@db:5432/prisma?schema=public
    depends_on:
      db:
        condition: service_healthy