services:
  app:
    build:
      context: ./front-end
    image: ghcr.io/jcubby86/games-app:${DOCKER_TAG:-latest}
    ports:
      - ${WEB_PORT:-80}:80
    environment:
      - NGINX_BACKEND_ADDRESS=http://backend:${NODE_PORT:-3000}
      - NODE_ENV=${NODE_ENV}
    restart: unless-stopped
    depends_on: 
      - backend
      - db

  backend:
    build:
      context: ./back-end
    image: ghcr.io/jcubby86/games-backend:${DOCKER_TAG:-latest}
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/prisma?schema=public
      - NODE_PORT=${NODE_PORT:-3000}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test:  wget --spider --tries=1 --no-verbose http://localhost:${NODE_PORT:-3000}/health
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
    depends_on:
      db:
        condition: service_healthy
      
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /portainer/postgres/games-${NODE_ENV}:/var/lib/postgresql/data
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120