services:
  app:
    image: ghcr.io/jcubby86/games-app:${DOCKER_TAG:-latest}
    ports:
      - ${WEB_PORT:-80}:80
    environment:
      - NGINX_BACKEND_ADDRESS=http://backend:${NODE_PORT:-3000}
    restart: unless-stopped
    depends_on: 
      - backend
      - db

  backend:
    image: ghcr.io/jcubby86/games-backend:${DOCKER_TAG:-latest}
    environment:
      - MONGO_DB_CONN_STR=mongodb://db/games
      - NODE_PORT=${NODE_PORT:-3000}
    restart: unless-stopped
    depends_on: 
      - db
    healthcheck:
      test:  wget --spider --tries=1 --no-verbose http://localhost:${NODE_PORT:-3000}/api/health
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 10s
      
  db:
    image: mongo:latest
    volumes:
    - /portainer/mongo-games-${ENV:-test}:/data/db
    restart: unless-stopped
    
  db-seed:
    image: byrnedo/alpine-curl
    command: "-X POST http://backend:${NODE_PORT:-3000}/api/seed"
    depends_on:
      backend:
        condition: service_healthy
      db:
        condition: service_started