version: '3'
services:
  app:
    container_name: games-app
    image: games-app:0.0.0
    ports:
    - '3020:80'
    environment:
    - NGINX_BACKEND_ADDRESS=http://games-backend:3000

  backend: 
    container_name: games-backend
    image: games-backend:0.0.0
    ports:
    - '3000'
    environment:
    - MONGO_DB_CONN_STR=mongodb://192.168.86.81:27017/games-cp4
    - NODE_PORT=3000
