version: '3'
services:
  app:
    container_name: games-app
    build:
      context: ./front-end
      tags:
        - 'games-app:1.1.0'
        - 'games-app:latest'
    image: games-app:latest
    ports:
      - '3020:80'
    environment:
      - NGINX_BACKEND_ADDRESS=http://games-backend:3000

  backend:
    container_name: games-backend
    build:
      context: ./back-end
      tags:
        - 'games-backend:1.1.0'
        - 'games-backend:latest'
    image: games-backend:latest
    ports:
      - '3000'
    environment:
      - MONGO_DB_CONN_STR=mongodb://192.168.86.81:27017/games-cp4
      - NODE_PORT=3000
