export default [
  'So they threw coins off the top of the space needle trying to hit people. But soon upgraded to water balloons',
  'Got married of course! ',
  'Locked pinkies and skipped off into the sunset, singing Somewhere Over the Rainbow',
  'Left to go look for their digits',
  'Went gravesite shopping at the cemetery for their vacation. ',
  'Put on their big boy pants and stepped into moving traffic',
  'So they solved world hunger, cured cancer, and explored the deepest parts of the ocean',
  'went skydiving with the dog.',
  'read a book with a baby',
  'ate all of the spaghettis',
  'huffed and puffed and blew the house down',
  'cried every time',
  "attempted to put on each other's straight jackets but you can't put on someone else's while you are wearing one.",
  'Sold their birthrights for some stronger lungs.',
  'Jumped on the trees and jumped on the houses and punched peoples cars ',
  'wrestled in a vat of warm milk and one of them died.',
  'Physically entered the portal to the virtual world of the video game to save their cousin, but died from a squirtle.',
  'Went camping in a haunted motorhome and the ghost Nate their spam',
  'Went alligator surfing during the hurricane in florida and saved all the flamingos',
  'So she fell into the pit of quicksand as he screamed in terror, but she only sank down to her ankles so it ended up being fine. ',
  'Retired from milking goats and started a business milking almonds ',
  'Ran away',
  'Frolicked throughout the corn maze until they arrived at the yellow brick road',
];
