export default [
  'dancing in the rain',
  'eating spaghetti',
  'driving to the airport',
  'sledding down the hill',
  'writing love letters',
  'watching Shrek 2',
  'washing potatoes',
  'listening to white noise',
  'snuggling with stuffed animals',
  'reading a good book',
  'coding up a fun game',
  'Dancing to that song Walk like a man like ya know in that song walk like a man. ',
  'Bickering over who killed who',
  'Being towed in a wagon while in the Running of the Bulls',
  'Scuba diving in a pool of Jello ',
  'Hiding from a murderer in a closet while talking loudly on a phone',
  'Playing mine sweeper looking to kill cute ducks',
  'Skipping down main street singing Christmas carols. ',
  'Eating their curds and whey. Gross.',
  'walking on the beach and throwing the jellyfish back in the ocean',
  'Selling Seashells by the homeless man in an abandoned subway tunnel',
  'Looking lovingly into each others eyes. Gross.',
  'separating the good water from the bad water and punishing the bad water',
  'Particle colliding in their free time.',
  'Watching a dcumentary about cannibalism',
  'Eating ice cream at a pizza place in new york',
  'Gossiping',
];
