export default [
  'dancing in the rain',
  'eating spaghetti',
  'driving to the airport',
  'sledding down the hill',
  'writing love letters',
  'watching Shrek 2',
  'washing potatoes',
  'listening to white noise',
  'snuggling with stuffed animals',
  'reading a good book',
  'coding up a fun game',
  'Dancing to that song Walk like a man like ya know in that song walk like a man. ',
  'Bickering over who killed who',
  'Being towed in a wagon while in the Running of the Bulls',
  'Scuba diving in a pool of Jello ',
  'Hiding from a murderer in a closet while talking loudly on a phone',
  'Playing mine sweeper looking to kill cute ducks',
];
