export default [
  'I like cheese',
  'What did you call me?',
  'Why are you so mean?',
  'Did you mean to call or was it an accident?',
  'Look out!',
  'My reflexes are just fine, look!',
  "Don't throw that away, it could be useful!",
  'Wait for me!',
  'Okay, but no mayonnaise this time',
  'Can you grab the weekwhacker? I need to shave my back again',
  "Ok let's go change. And this time I get the sparkly pink jumpsuit!",
  "I haven't thrown a great, big tantrum in a while...",
  'Will you marry me? ',
  'Really? I thought I was the only one!',
  'We need to bring back milk men.',
  'I am woman hear me roar',
  "I don't read good",
  "Stop breathing.  It's annoying!",
  'Oh, what a beautiful mid-morning!',
  "It's my birthday and I'll cry if I want to, cry if I want to, cry cry cry CRY",
];
