export default [
  'I like cheese',
  'What did you call me?',
  'Why are you so mean?',
  'Did you mean to call or was it an accident?',
  'Look out!',
  'My reflexes are just fine, look!',
  "Don't throw that away, it could be useful!",
  'Wait for me!',
  'Okay, but no mayonnaise this time',
  'Can you grab the weekwhacker? I need to shave my back again',
  "Ok let's go change. And this time I get the sparkly pink jumpsuit!",
  "I haven't thrown a great, big tantrum in a while...",
  'Will you marry me? ',
  'Really? I thought I was the only one!',
  'We need to bring back milk men.',
  'I am woman hear me roar',
  "I don't read good",
  "Stop breathing.  It's annoying!",
  'Oh, what a beautiful mid-morning!',
  "It's my birthday and I'll cry if I want to, cry if I want to, cry cry cry CRY",
  "I can't hear you over my inner demons ",
  'McDonals forgot my McNuggets….. we are about to have a McProblem',
  'Boost my bottom!!!',
  "I don't think we need to bring China into this",
  'I thought we were just changing a lightbulb, how did we end up here?',
  "It's hard to tap dance on the beach",
  'I love it when I stroll grandly through the ocean',
  'Make sure to save the wrapping paper and the bows',
  "I didn't even think the new Star Wars movies were that bad",
  'Quick, let me feel!',
  'New phone, who dis?',
  "Stop exhaling — you're ruining the air and making the earth toxic",
  'If you could be the one who if you were the greatest then if you were who you wanted to be for your parents?',
  'I hate to tell you this / but I have leprosy ',
  'You woke me up for this?!?',
  'What the frick?',
  'Well I never',
  "I don't care who your mother is, I am going to get on that boat",
  "That's what she said",
  'Have you seen my spleen?',
  'Time to wake up to WOKE, fool.',
  'Thinks for thanking of me',
  "I'm not as think as you drunk I am, ocifer",
];
